version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Map host port 5000 to container port 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80 # Ensure app listens on port 80 inside the container
    volumes:
      - ./logs:/app/logs # Map logs directory for persistence
